from .statistical_analysis import run_statistical_analysis
from .evolutionary_analysis import run_evolutionary_analysis
from .detailed_analysis import run_detailed_analysis
from .detailed_statistical_analysis import display_detailed_statistical_analysis
